-- ============================================================================
-- GLOBAL ALARM — PHASE 1: alarm_events
--
-- Target database : hvac_current
-- Target table    : alarm_events   (exactly ONE new table)
--
-- PREPARED ONLY — NOT YET EXECUTED.
-- The account available to the assistant (`hvac_web`) has SELECT-only rights on
-- hvac_current and cannot CREATE. Per GLOBAL_ALARM_PHASE1_FINAL_GO.md, this DDL
-- is returned for MANUAL execution. No credentials were probed.
--
-- Run this against BOTH databases when the hosting side is ready:
--   local  : hvac_current      (XAMPP, 127.0.0.1)
--   remote : u468140406_hvac   (Hostinger, srv1763.hstgr.io)
-- The DDL is byte-identical for both; utf8mb4_unicode_ci matches the project
-- convention so a straight replay produces the same table.
--
-- This statement creates one table and touches nothing else. It contains no
-- ALTER, DROP, DELETE, TRUNCATE, RENAME, or INSERT, and defines no foreign key.
-- Safe to re-run: IF NOT EXISTS makes it a no-op once the table exists.
-- ============================================================================

CREATE TABLE IF NOT EXISTS `alarm_events` (

    -- ------------------------------------------------------------------
    -- Identity
    -- ------------------------------------------------------------------
    `id`            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    -- Append-heavy event log; one row per alarm occurrence. An alarm may
    -- recur many times, so there is no stable natural key. BIGINT sizes the
    -- log for years of events at a 30-second poll cadence.

    -- ------------------------------------------------------------------
    -- Classification
    -- ------------------------------------------------------------------
    `event_class`   ENUM('ALARM','WARNING') NOT NULL,
    -- The primary distinction, and the only one Phase 1 defines:
    --   ALARM   = generated by a native equipment alarm/status point
    --   WARNING = generated by a threshold / value-limit violation
    -- The two are never converted into one another, and one piece of
    -- equipment may legitimately hold both at the same time as separate rows.

    `source`        VARCHAR(32) NOT NULL,
    -- The originating writer/poller, e.g. AHU_POLLER, HVAC_SC_POLLER,
    -- EF_POLLER, ROOM_POLLER. Deliberately VARCHAR, not ENUM, so a new
    -- poller can be introduced without an ALTER.

    -- ------------------------------------------------------------------
    -- Equipment / point identity
    -- ------------------------------------------------------------------
    `equip_type`    VARCHAR(50)  NULL,
    -- Equipment classification using actual project values, e.g. 'AHU',
    -- 'CHILLER', 'CCP', 'CHWP', 'CT', 'ROOM TEMP & RH'.
    -- NOTE: source data currently stores CT as 'CT ' with a trailing space.
    -- Phase 1 does NOT alter that source data; the future poller contract
    -- must TRIM() before writing so UI filters stay consistent.

    `equipment`     VARCHAR(64)  NOT NULL,
    -- Human-readable equipment identity for the alarm page: 'AHU 65',
    -- 'CCP 3', 'EF 27', 'CT 5A', 'ROOM 1056', 'Panel 3'.

    `point_id`      VARCHAR(32)  NULL,
    -- points.point_id for normal project points (AHU / HVAC_SC / ROOM).
    -- Matches points.point_id VARCHAR(32); actual max length in data is 17.

    `ef_point_id`   INT UNSIGNED NULL,
    -- ef_points.id, for EF point identity. Matches ef_points.id INT UNSIGNED.

    `panel_no`      INT          NULL,
    -- Reserved for sources where panel identity is authoritative, especially
    -- EF communication/event context. EF alarm granularity is intentionally
    -- NOT decided in Phase 1.

    `ip_address`    VARCHAR(45)  NULL,
    -- Communication-source identity where IP is relevant.
    -- VARCHAR(45) matches ef_points.ip_address and holds IPv6.

    `metric`        VARCHAR(32)  NULL,
    -- Optional point/measurement detail: TEMP, RH, CURRENT, STATUS.
    -- No further metric taxonomy is invented in Phase 1.

    `description`   VARCHAR(255) NOT NULL,
    -- Human-readable alarm text for the global alarm page.

    -- ------------------------------------------------------------------
    -- Lifecycle + duplicate prevention
    -- ------------------------------------------------------------------
    `status`        ENUM('ACTIVE','CLEARED') NOT NULL DEFAULT 'ACTIVE',
    -- Current lifecycle state of the event.

    `active_key`    VARCHAR(200) NULL,
    -- Deterministic identity of an ACTIVE alarm condition; the sole
    -- duplicate-prevention mechanism. Set while ACTIVE, NULL once CLEARED.
    -- MariaDB allows multiple NULLs in a UNIQUE index, so any number of
    -- CLEARED rows coexist while at most one ACTIVE row per identity exists.
    -- Identity examples (poller contract is future work):
    --   NATIVE_ALARM:<point_id>:<metric>
    --   THRESHOLD_AI:<point_id>:<metric>:<max|min>
    --   EF_POINT:<ef_point_id>:<metric>
    --   EF_COMM:<panel_no>

    -- ------------------------------------------------------------------
    -- Value + limit frozen at alarm time
    -- ------------------------------------------------------------------
    `value`         FLOAT NULL,
    -- Actual value captured when the alarm was raised. NULL where not
    -- applicable (e.g. a native status alarm). Stored here because
    -- ai_current / bi_current are overwritten in place and cannot be used
    -- later to reconstruct the value at alarm time.

    `limit_min`     FLOAT NULL,
    -- Lower threshold, when applicable.

    `limit_max`     FLOAT NULL,
    -- Upper threshold, when applicable. For a simple high-limit warning only
    -- limit_max is populated (all current project thresholds are upper-bound;
    -- every min_value in threshold_direct / threshold_by_kw is NULL today).

    -- ------------------------------------------------------------------
    -- Time (naive WIB — see note below)
    -- ------------------------------------------------------------------
    `raised_at`     DATETIME(6) NOT NULL,
    -- Raise timestamp, supplied explicitly by the poller.
    -- NO DEFAULT CURRENT_TIMESTAMP on purpose: the project stores naive WIB
    -- timestamps; the local DB SYSTEM timezone is WIB but the hosting DB
    -- SYSTEM timezone is UTC, so a database-generated NOW()/CURRENT_TIMESTAMP
    -- would silently produce inconsistent timestamps between the two hosts.
    -- DATETIME(6) matches the existing event tables ef_alarm_events and
    -- ef_communication_events, whose event_time is DATETIME(6).

    `cleared_at`    DATETIME(6) NULL,
    -- Explicit recovery timestamp supplied by the poller. Same no-default
    -- rule as raised_at.
    -- DURATION is derived at read time, never stored:
    --   TIMESTAMPDIFF(SECOND, raised_at, cleared_at)

    -- ------------------------------------------------------------------
    -- Keys
    -- ------------------------------------------------------------------
    PRIMARY KEY (`id`),

    UNIQUE KEY `uq_alarm_active` (`active_key`),
    -- Enforces at most one ACTIVE row per alarm identity.

    KEY `idx_alarm_raised`   (`raised_at`),
    KEY `idx_alarm_status`   (`status`, `raised_at`),
    KEY `idx_alarm_equip`    (`equip_type`, `raised_at`),
    KEY `idx_alarm_point`    (`point_id`, `raised_at`),
    KEY `idx_alarm_ef_point` (`ef_point_id`, `raised_at`),
    KEY `idx_alarm_class`    (`event_class`, `raised_at`),
    -- One index per future alarm-page filter (All/Active/Cleared, equipment,
    -- point, class), each leading with a time column so ORDER BY ... DESC
    -- stays index-ordered. No further indexes added.

    CONSTRAINT `chk_alarm_active_state` CHECK (
        (`status` = 'ACTIVE'  AND `active_key` IS NOT NULL)
        OR
        (`status` = 'CLEARED' AND `active_key` IS NULL)
    )
    -- Prevents status and active_key from drifting into an inconsistent state.

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- No foreign keys on alarm_events (as required by the Phase 1 spec).
--
-- Note on the project convention: 20 of the 21 existing tables define no
-- foreign key. There is exactly ONE legacy exception —
-- ef_alarm_events.fk_ef_alarm_point -> ef_points(id).
--
-- alarm_events deliberately defines none, for a reason beyond convention:
-- point_id / ef_point_id / panel_no are intentionally nullable and
-- polymorphic (a row carries whichever identity its source uses, and a
-- communication event carries neither point_id nor ef_point_id). A foreign
-- key cannot express that, and one on point_id would additionally force the
-- poller's write order and block point renumbering.
--
-- No ALTER, DROP, DELETE, TRUNCATE, RENAME, or INSERT is performed here.
-- ============================================================================


-- ============================================================================
-- POST-CREATE VERIFICATION (read-only — run after the CREATE above)
-- ============================================================================

-- 1. Table exists in hvac_current
-- SELECT COUNT(*) AS alarm_events_exists
-- FROM information_schema.TABLES
-- WHERE TABLE_SCHEMA='hvac_current' AND TABLE_NAME='alarm_events';

-- 2. Full DDL as stored by the server
-- SHOW CREATE TABLE hvac_current.alarm_events;

-- 3. Columns
-- DESCRIBE hvac_current.alarm_events;

-- 4. Indexes
-- SHOW INDEX FROM hvac_current.alarm_events;

-- 5. CHECK constraint exists
-- SELECT CONSTRAINT_NAME, CHECK_CLAUSE
-- FROM information_schema.CHECK_CONSTRAINTS
-- WHERE CONSTRAINT_SCHEMA='hvac_current' AND TABLE_NAME='alarm_events';

-- 6. UNIQUE(active_key) exists
-- SELECT INDEX_NAME, NON_UNIQUE, COLUMN_NAME
-- FROM information_schema.STATISTICS
-- WHERE TABLE_SCHEMA='hvac_current' AND TABLE_NAME='alarm_events'
--   AND INDEX_NAME='uq_alarm_active';

-- 7. No existing table was modified — compare against the baseline captured
--    immediately BEFORE this CREATE (read-only, from authoritative sources):
--      tables                : 21  (every one has a PRIMARY KEY)
--      foreign keys          : 1   (ef_alarm_events.fk_ef_alarm_point only)
--      check constraints     : 1   (temp_rh_hourly.chk_metric only)
--      columns_md5           : 0404ee27ce38657baaccff745220c8f0
--      indexes_md5           : 617c93073325efdc9568ab5b9dd8afc6
--      rowcounts_md5         : 5b94187967b42fab65b029c572b6765a
--
--    CAUTION: the constraints_md5 fingerprint taken earlier was DISCARDED as
--    unreliable — information_schema.TABLE_CONSTRAINTS returned only 7 PRIMARY
--    KEY rows for 21 tables, so it silently under-reports. Use the FK count,
--    CHECK count and the STATISTICS-based indexes_md5 above instead.
--
--    Re-run these after CREATE. The counts must be UNCHANGED (21 / 1 / 1) and
--    the MD5s must be IDENTICAL, with the new table excluded from each query:
--
-- SET SESSION group_concat_max_len = 10000000;
-- SELECT COUNT(*) FROM information_schema.TABLES
--   WHERE TABLE_SCHEMA='hvac_current' AND TABLE_NAME <> 'alarm_events';
-- SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE
--   WHERE TABLE_SCHEMA='hvac_current' AND REFERENCED_TABLE_NAME IS NOT NULL;
-- SELECT COUNT(*) FROM information_schema.CHECK_CONSTRAINTS
--   WHERE CONSTRAINT_SCHEMA='hvac_current' AND TABLE_NAME <> 'alarm_events';
-- SELECT MD5(GROUP_CONCAT(CONCAT_WS(':',TABLE_NAME,COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,IFNULL(COLUMN_DEFAULT,'~'),EXTRA) ORDER BY TABLE_NAME,ORDINAL_POSITION SEPARATOR '|')) AS columns_md5
--   FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='hvac_current' AND TABLE_NAME <> 'alarm_events';
-- SELECT MD5(GROUP_CONCAT(CONCAT_WS(':',TABLE_NAME,INDEX_NAME,NON_UNIQUE,SEQ_IN_INDEX,COLUMN_NAME) ORDER BY TABLE_NAME,INDEX_NAME,SEQ_IN_INDEX SEPARATOR '|')) AS indexes_md5
--   FROM information_schema.STATISTICS WHERE TABLE_SCHEMA='hvac_current' AND TABLE_NAME <> 'alarm_events';
-- SELECT MD5(GROUP_CONCAT(CONCAT_WS(':',TABLE_NAME,TABLE_ROWS) ORDER BY TABLE_NAME SEPARATOR '|')) AS rowcounts_md5
--   FROM information_schema.TABLES WHERE TABLE_SCHEMA='hvac_current' AND TABLE_NAME <> 'alarm_events';


-- ============================================================================
-- TEST CONCEPT (reversible) — DO NOT RUN until the table exists AND the user
-- approves test execution. Wrap in a transaction and ROLLBACK so no fake row
-- is left in production.
-- ============================================================================
--
-- START TRANSACTION;
--
-- -- 1. WARNING ACTIVE
-- INSERT INTO alarm_events
--   (event_class, source, equip_type, equipment, point_id, metric,
--    description, status, active_key, value, limit_max, raised_at)
-- VALUES
--   ('WARNING','AHU_POLLER','AHU','AHU 65','0010203AI0000123','TEMP',
--    'AHU 65 supply temperature 28.4 C above limit 25 C',
--    'ACTIVE','THRESHOLD_AI:0010203AI0000123:TEMP:max', 28.4, 25, NOW(6));
--
-- -- 2./3. Attempt duplicate ACTIVE identity -> must FAIL with
-- --       ERROR 1062 (23000): Duplicate entry ... for key 'uq_alarm_active'
-- INSERT INTO alarm_events
--   (event_class, source, equip_type, equipment, point_id, metric,
--    description, status, active_key, value, limit_max, raised_at)
-- VALUES
--   ('WARNING','AHU_POLLER','AHU','AHU 65','0010203AI0000123','TEMP',
--    'duplicate probe','ACTIVE','THRESHOLD_AI:0010203AI0000123:TEMP:max',
--    28.5, 25, NOW(6));
--
-- -- 4./5. Clear -> active_key becomes NULL, status CLEARED
-- UPDATE alarm_events
--    SET status='CLEARED', cleared_at=NOW(6), active_key=NULL
--  WHERE active_key='THRESHOLD_AI:0010203AI0000123:TEMP:max';
--
-- -- 6./7. Same alarm recurs -> a NEW row must be insertable
-- INSERT INTO alarm_events
--   (event_class, source, equip_type, equipment, point_id, metric,
--    description, status, active_key, value, limit_max, raised_at)
-- VALUES
--   ('WARNING','AHU_POLLER','AHU','AHU 65','0010203AI0000123','TEMP',
--    'AHU 65 supply temperature 26.1 C above limit 25 C',
--    'ACTIVE','THRESHOLD_AI:0010203AI0000123:TEMP:max', 26.1, 25, NOW(6));
--
-- -- Also worth asserting (both must FAIL, proving the CHECK works):
-- --   ACTIVE  with active_key NULL
-- --   CLEARED with active_key NOT NULL
--
-- ROLLBACK;   -- leaves no test rows in production
--
-- ============================================================================
